project_id = "ribbon"

[api]
enabled = true
port = 56321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17
port = 56322
shadow_port = 56320

[studio]
enabled = true
port = 56323

[inbucket]
enabled = true
port = 56324
smtp_port = 56325
pop3_port = 56326

[analytics]
enabled = true
port = 56327

[storage.vector]
enabled = false

[auth]
enabled = true
site_url = "https://ribbon.moriatz.com"
additional_redirect_urls = ["https://ribbon.moriatz.com", "https://ribbon-silk.vercel.app", "http://127.0.0.1:4310", "http://localhost:4310"]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "60s"
otp_expiry = 3600

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
